
import type { FoodItem, Reminder } from '@/types';

export const foodDatabase: FoodItem[] = [
  // Lebanese Foods
  {
    id: 'l1',
    nameEn: 'Hummus',
    nameAr: 'حمص',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '2 tbsp (30g)',
    servingSizeAr: '2 ملعقة كبيرة (30غ)',
    potassium: 137,
    phosphorus: 55,
    sodium: 150,
    protein: 3.8,
  },
  {
    id: 'l2',
    nameEn: 'Tabbouleh',
    nameAr: 'تبولة',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '1 cup (100g)',
    servingSizeAr: '1 كوب (100غ)',
    potassium: 450,
    phosphorus: 35,
    sodium: 120,
    protein: 2.5,
  },
  {
    id: 'l3',
    nameEn: 'Falafel',
    nameAr: 'فلافل',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '2 pieces (50g)',
    servingSizeAr: '2 قطعة (50غ)',
    potassium: 170,
    phosphorus: 90,
    sodium: 280,
    protein: 6.5,
  },
  {
    id: 'l4',
    nameEn: 'Kibbeh',
    nameAr: 'كبة',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '1 piece (75g)',
    servingSizeAr: '1 قطعة (75غ)',
    potassium: 210,
    phosphorus: 130,
    sodium: 320,
    protein: 12,
  },
  {
    id: 'l5',
    nameEn: 'Labneh',
    nameAr: 'لبنة',
    category: 'dairy',
    categoryAr: 'منتجات ألبان',
    servingSize: '2 tbsp (30g)',
    servingSizeAr: '2 ملعقة كبيرة (30غ)',
    potassium: 80,
    phosphorus: 70,
    sodium: 45,
    protein: 4,
  },
  {
    id: 'l6',
    nameEn: 'Fattoush',
    nameAr: 'فتوش',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '1 cup (150g)',
    servingSizeAr: '1 كوب (150غ)',
    potassium: 380,
    phosphorus: 45,
    sodium: 180,
    protein: 2,
  },
  {
    id: 'l7',
    nameEn: 'Baba Ghanoush',
    nameAr: 'متبل',
    category: 'lebanese',
    categoryAr: 'لبناني',
    servingSize: '2 tbsp (30g)',
    servingSizeAr: '2 ملعقة كبيرة (30غ)',
    potassium: 200,
    phosphorus: 25,
    sodium: 140,
    protein: 1.5,
  },
  {
    id: 'l8',
    nameEn: 'Shawarma Chicken',
    nameAr: 'شاورما دجاج',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g',
    servingSizeAr: '100غ',
    potassium: 280,
    phosphorus: 180,
    sodium: 450,
    protein: 22,
  },
  {
    id: 'l9',
    nameEn: 'Manakish Zaatar',
    nameAr: 'مناقيش زعتر',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 piece (100g)',
    servingSizeAr: '1 قطعة (100غ)',
    potassium: 180,
    phosphorus: 85,
    sodium: 320,
    protein: 7,
  },
  {
    id: 'l10',
    nameEn: 'Grilled Chicken',
    nameAr: 'دجاج مشوي',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g',
    servingSizeAr: '100غ',
    potassium: 250,
    phosphorus: 200,
    sodium: 70,
    protein: 31,
  },

  // Grains
  {
    id: 'g1',
    nameEn: 'White Rice',
    nameAr: 'أرز أبيض',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 cup cooked (158g)',
    servingSizeAr: '1 كوب مطبوخ (158غ)',
    potassium: 55,
    phosphorus: 68,
    sodium: 5,
    protein: 4.3,
  },
  {
    id: 'g2',
    nameEn: 'Brown Rice',
    nameAr: 'أرز بني',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 cup cooked (195g)',
    servingSizeAr: '1 كوب مطبوخ (195غ)',
    potassium: 150,
    phosphorus: 150,
    sodium: 10,
    protein: 5,
  },
  {
    id: 'g3',
    nameEn: 'White Bread',
    nameAr: 'خبز أبيض',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 slice (28g)',
    servingSizeAr: '1 شريحة (28غ)',
    potassium: 35,
    phosphorus: 30,
    sodium: 130,
    protein: 2.7,
  },
  {
    id: 'g4',
    nameEn: 'Whole Wheat Bread',
    nameAr: 'خبز أسمر',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 slice (28g)',
    servingSizeAr: '1 شريحة (28غ)',
    potassium: 70,
    phosphorus: 60,
    sodium: 140,
    protein: 4,
  },
  {
    id: 'g5',
    nameEn: 'Pasta',
    nameAr: 'معكرونة',
    category: 'grains',
    categoryAr: 'حبوب',
    servingSize: '1 cup cooked (140g)',
    servingSizeAr: '1 كوب مطبوخ (140غ)',
    potassium: 60,
    phosphorus: 80,
    sodium: 10,
    protein: 5,
  },

  // Protein
  {
    id: 'p1',
    nameEn: 'Chicken Breast',
    nameAr: 'صدر دجاج',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g cooked',
    servingSizeAr: '100غ مطبوخ',
    potassium: 250,
    phosphorus: 200,
    sodium: 70,
    protein: 31,
  },
  {
    id: 'p2',
    nameEn: 'Salmon',
    nameAr: 'سلمون',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g cooked',
    servingSizeAr: '100غ مطبوخ',
    potassium: 360,
    phosphorus: 200,
    sodium: 60,
    protein: 25,
  },
  {
    id: 'p3',
    nameEn: 'Egg',
    nameAr: 'بيضة',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '1 large (50g)',
    servingSizeAr: '1 كبيرة (50غ)',
    potassium: 70,
    phosphorus: 100,
    sodium: 70,
    protein: 6,
  },
  {
    id: 'p4',
    nameEn: 'Tuna',
    nameAr: 'تونة',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g canned',
    servingSizeAr: '100غ معلبة',
    potassium: 230,
    phosphorus: 200,
    sodium: 350,
    protein: 28,
  },
  {
    id: 'p5',
    nameEn: 'Lamb',
    nameAr: 'حمل',
    category: 'protein',
    categoryAr: 'بروتين',
    servingSize: '100g cooked',
    servingSizeAr: '100غ مطبوخ',
    potassium: 320,
    phosphorus: 180,
    sodium: 70,
    protein: 25,
  },

  // Fruits
  {
    id: 'f1',
    nameEn: 'Apple',
    nameAr: 'تفاحة',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 medium (182g)',
    servingSizeAr: '1 متوسطة (182غ)',
    potassium: 195,
    phosphorus: 20,
    sodium: 2,
    protein: 0.5,
  },
  {
    id: 'f2',
    nameEn: 'Banana',
    nameAr: 'موزة',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 medium (118g)',
    servingSizeAr: '1 متوسطة (118غ)',
    potassium: 422,
    phosphorus: 25,
    sodium: 1,
    protein: 1.3,
  },
  {
    id: 'f3',
    nameEn: 'Orange',
    nameAr: 'برتقالة',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 medium (131g)',
    servingSizeAr: '1 متوسطة (131غ)',
    potassium: 237,
    phosphorus: 35,
    sodium: 1,
    protein: 1.2,
  },
  {
    id: 'f4',
    nameEn: 'Grapes',
    nameAr: 'عنب',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 cup (151g)',
    servingSizeAr: '1 كوب (151غ)',
    potassium: 288,
    phosphorus: 30,
    sodium: 3,
    protein: 1.1,
  },
  {
    id: 'f5',
    nameEn: 'Strawberries',
    nameAr: 'فراولة',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 cup (152g)',
    servingSizeAr: '1 كوب (152غ)',
    potassium: 247,
    phosphorus: 35,
    sodium: 4,
    protein: 1,
  },
  {
    id: 'f6',
    nameEn: 'Watermelon',
    nameAr: 'بطيخ',
    category: 'fruits',
    categoryAr: 'فواكه',
    servingSize: '1 cup (152g)',
    servingSizeAr: '1 كوب (152غ)',
    potassium: 170,
    phosphorus: 20,
    sodium: 3,
    protein: 1,
  },

  // Vegetables
  {
    id: 'v1',
    nameEn: 'Tomato',
    nameAr: 'طماطم',
    category: 'vegetables',
    categoryAr: 'خضروات',
    servingSize: '1 medium (123g)',
    servingSizeAr: '1 متوسطة (123غ)',
    potassium: 292,
    phosphorus: 30,
    sodium: 5,
    protein: 1.1,
  },
  {
    id: 'v2',
    nameEn: 'Cucumber',
    nameAr: 'خيار',
    category: 'vegetables',
    categoryAr: 'خضروات',
    servingSize: '1 medium (300g)',
    servingSizeAr: '1 متوسطة (300غ)',
    potassium: 440,
    phosphorus: 50,
    sodium: 6,
    protein: 2,
  },
  {
    id: 'v3',
    nameEn: 'Carrot',
    nameAr: 'جزر',
    category: 'vegetables',
    categoryAr: 'خضروات',
    servingSize: '1 medium (61g)',
    servingSizeAr: '1 متوسطة (61غ)',
    potassium: 195,
    phosphorus: 25,
    sodium: 42,
    protein: 0.6,
  },
  {
    id: 'v4',
    nameEn: 'Broccoli',
    nameAr: 'بروكلي',
    category: 'vegetables',
    categoryAr: 'خضروات',
    servingSize: '1 cup chopped (91g)',
    servingSizeAr: '1 كوب مقطع (91غ)',
    potassium: 230,
    phosphorus: 70,
    sodium: 33,
    protein: 2.5,
  },
  {
    id: 'v5',
    nameEn: 'Lettuce',
    nameAr: 'خس',
    category: 'vegetables',
    categoryAr: 'خضروات',
    servingSize: '1 cup shredded (36g)',
    servingSizeAr: '1 كوب مبشور (36غ)',
    potassium: 70,
    phosphorus: 20,
    sodium: 10,
    protein: 0.7,
  },

  // Fats & Oils
  {
    id: 'o1',
    nameEn: 'Olive Oil',
    nameAr: 'زيت زيتون',
    category: 'fats',
    categoryAr: 'دهون وزيوت',
    servingSize: '1 tbsp (14g)',
    servingSizeAr: '1 ملعقة كبيرة (14غ)',
    potassium: 0,
    phosphorus: 0,
    sodium: 0,
    protein: 0,
  },
  {
    id: 'o2',
    nameEn: 'Butter',
    nameAr: 'زبدة',
    category: 'fats',
    categoryAr: 'دهون وزيوت',
    servingSize: '1 tbsp (14g)',
    servingSizeAr: '1 ملعقة كبيرة (14غ)',
    potassium: 2,
    phosphorus: 2,
    sodium: 100,
    protein: 0.1,
  },

  // Dairy
  {
    id: 'd1',
    nameEn: 'Milk',
    nameAr: 'حليب',
    category: 'dairy',
    categoryAr: 'منتجات ألبان',
    servingSize: '1 cup (240ml)',
    servingSizeAr: '1 كوب (240مل)',
    potassium: 380,
    phosphorus: 230,
    sodium: 100,
    protein: 8,
  },
  {
    id: 'd2',
    nameEn: 'Greek Yogurt',
    nameAr: 'زبادي يوناني',
    category: 'dairy',
    categoryAr: 'منتجات ألبان',
    servingSize: '1 cup (245g)',
    servingSizeAr: '1 كوب (245غ)',
    potassium: 280,
    phosphorus: 240,
    sodium: 70,
    protein: 23,
  },
  {
    id: 'd3',
    nameEn: 'Cheese',
    nameAr: 'جبنة',
    category: 'dairy',
    categoryAr: 'منتجات ألبان',
    servingSize: '1 oz (28g)',
    servingSizeAr: '1 أونصة (28غ)',
    potassium: 20,
    phosphorus: 140,
    sodium: 180,
    protein: 7,
  },

  // Beverages
  {
    id: 'b1',
    nameEn: 'Water',
    nameAr: 'ماء',
    category: 'beverages',
    categoryAr: 'مشروبات',
    servingSize: '1 cup (240ml)',
    servingSizeAr: '1 كوب (240مل)',
    potassium: 0,
    phosphorus: 0,
    sodium: 0,
    protein: 0,
  },
  {
    id: 'b2',
    nameEn: 'Coffee',
    nameAr: 'قهوة',
    category: 'beverages',
    categoryAr: 'مشروبات',
    servingSize: '1 cup (240ml)',
    servingSizeAr: '1 كوب (240مل)',
    potassium: 116,
    phosphorus: 5,
    sodium: 5,
    protein: 0.3,
  },
  {
    id: 'b3',
    nameEn: 'Tea',
    nameAr: 'شاي',
    category: 'beverages',
    categoryAr: 'مشروبات',
    servingSize: '1 cup (240ml)',
    servingSizeAr: '1 كوب (240مل)',
    potassium: 88,
    phosphorus: 2,
    sodium: 5,
    protein: 0,
  },

  // Sweeteners
  {
    id: 's1',
    nameEn: 'Sugar',
    nameAr: 'سكر',
    category: 'sweeteners',
    categoryAr: 'محليات',
    servingSize: '1 tsp (4g)',
    servingSizeAr: '1 ملعقة صغيرة (4غ)',
    potassium: 0,
    phosphorus: 0,
    sodium: 0,
    protein: 0,
  },
  {
    id: 's2',
    nameEn: 'Honey',
    nameAr: 'عسل',
    category: 'sweeteners',
    categoryAr: 'محليات',
    servingSize: '1 tbsp (21g)',
    servingSizeAr: '1 ملعقة كبيرة (21غ)',
    potassium: 11,
    phosphorus: 1,
    sodium: 1,
    protein: 0.1,
  },
];

export const testimonials = [
  {
    id: 't1',
    nameEn: 'Fatima M.',
    nameAr: 'فاطمة م.',
    textEn: 'This app has made managing my potassium levels so much easier. The Lebanese food database is incredibly helpful!',
    textAr: 'هذا التطبيق جعل إدارة مستويات البوتاسيوم لدي أسهل بكثير. قاعدة بيانات الأطعمة اللبنانية مفيدة جداً!',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 't2',
    nameEn: 'Karim H.',
    nameAr: 'كريم ح.',
    textEn: 'Finally, an app designed for dialysis patients in the Middle East. The bilingual support is perfect for my family.',
    textAr: 'أخيراً، تطبيق مصمم لمرضى الغسيل الكلوي في الشرق الأوسط. الدعم ثنائي اللغة مثالي لعائلتي.',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 't3',
    nameEn: 'Nadia K.',
    nameAr: 'نادية ك.',
    textEn: 'My doctor loves the export reports. It helps us track my progress between appointments.',
    textAr: 'طبيبي يحب تقارير التصدير. يساعدنا في تتبع تقدمي بين المواعيد.',
    avatar: 'https://i.pravatar.cc/150?img=5',
  },
];
